name: playx_version_update_example
description: Demonstrates how to use the playx_version_update plugin.
version: '0.0.4+4'
publish_to: 'none'
environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  playx_version_update:
    path: ../

  cupertino_icons: ^1.0.8


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
